# Generated by Django 3.2 on 2022-01-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produce',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
