# Generated by Django 3.2 on 2022-01-29 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_produce_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produce',
            name='image_url',
        ),
    ]
